# Cloudflare Pages 配置
name = "femres"
compatibility_date = "2024-09-02"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "./dist"

# 开发环境变量 (生产环境请在 Cloudflare Dashboard 中设置)
[vars]
JWT_SECRET = "development-jwt-secret-change-in-production"

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "femres-db"
database_id = "your-d1-database-id-here"

# 生产环境配置 (实际值请在 Cloudflare Dashboard 中设置)
[env.production]
vars = { JWT_SECRET = "set-in-cloudflare-dashboard" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "femres-db"
database_id = "your-d1-database-id-here"